### ISSUE TITLE
5.4.0 (Development) Known bugs and todo

### ISSUE THREAD

**Issue by turt2live** [turt2live/AntiShare#33]
BUGS:
- [ ] Regions do not persist simple reloads (/as rl)

TODO:
- [ ] Add permissions change handling (#28)
- [ ] Split logic in listener to reduce size
- [ ] Unit tests
